FROM arm32v6/python:3.8-alpine3.12

VOLUME /config

COPY . /
RUN python -m pip install git+https://github.com/CoreTex/enocean.git
RUN python setup.py develop
RUN MKDIR /config

WORKDIR /
ENTRYPOINT ["python", "/usr/local/bin/enoceanmqtt", "/enoceanmqtt-default.conf", "/config/enoceanmqtt.conf"]
